inherit_from: .rubocop.yml

AllCops:
  DisabledByDefault: false
  DisplayCopNames: true

Layout/AlignArray:
  Enabled: false
Lint/Void:
  Exclude:
    - 'features/**/*'
    - 'spec/**/*'
Metrics/AbcSize:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/HashSyntax:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/TrailingCommaInArguments:
  Enabled: false
Style/TrailingCommaInLiteral:
  Enabled: false
Style/UnneededPercentQ:
  Enabled: false
